Official Documentation

https://numpy.org/doc/stable/user/index.html

# Installing the Library

Numpy doesn't come included with Python. So, we have to install and import it.

In [13]:
# Installs The Lastest Version of NumPy with pip, skip if installed with conda.
!pip3 install numpy --quiet # --quiet (or -q) flag limits the amount of information printed in the terminal.

In [14]:
# Check if Numpy is Installed Successfully.
!pip3 show numpy

Name: numpy
Version: 2.4.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, scikit-learn, scipy, seaborn


In [15]:
# We must import the external library every time we open this notebook to use it.
import numpy as np # here 'np' is an alias. 

# NumPy

A Basic Knowledge of NumPy.

NumPy (Numerical Python) is an open-source library that provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical functions to operate on these arrays.

At its core, NumPy provides the ndarray (n-dimensional array) data structure, which is highly optimized for efficient mathematical operations. This data structure allows you to store and manipulate large sets of data in a homogeneous and memory-efficient way. 

NumPy is a low-level library written in C for high-level mathematical functions. 
NumPy cleverly overcomes the problem of running slower algorithms on Python using multidimensional arrays and functions that operate on arrays. Any algorithm can then be expressed as a function on these arrays, allowing the algorithms to be run quickly.

Applications of NumPy

- A powerful N-dimensional array object.
- Sophisticated functions.
- Tools for integrating C/C++ and Fortran code.
- Useful linear algebra, Fourier transforms, and random number capabilities.

N-d Array Properties

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Properties of NumPy

- Homogenous (Only one type of data can be stored unlike Python Lists)
- Fixed item size (You can't directly add new elements to an array without creating a new one)

# Creating NumPy Arrays

These are various methods through which we can create NumPy arrays.

1. np.array()
2. np.zeros/ones/empty/random() functions.
4. np.arange()
5. np.linspace()
6. Copy()
7. np.identity()

In [20]:
# creating 1-dimension array (Vector)
arr1 = np.array([1,2,3,4,5],dtype='int16') 
print(arr1)

#dtype changes the datatype at will. Explained later.

[1 2 3 4 5]


In [21]:
# creating 2-dimension array (Matrix)
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [22]:
# creating 3-dimension array (Tensor)
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype='float64')
print(arr3)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [23]:
# type - Function returns the datatype of the object.
type(arr1) 

numpy.ndarray

In [24]:
# dtype - Create array with a custom datatype.
print(np.array([1,2,3,4,5],dtype=float))
print(np.array([1,2,3,4,5],dtype=bool))
print(np.array([1,2,3,4,5],dtype=complex))

[1. 2. 3. 4. 5.]
[ True  True  True  True  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [25]:
# Array size is passed as a tuple.
# Matrix made of zero of the given shape 
arr3 = np.zeros((2,3)) #
arr3 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#Array size is passed as a tuple.
# Matrix made of ones of the given shape 
arr4 = np.ones((3,4)) 
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#Identity Matrix
np.identity(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#N-Dim Array of Random Values (Float - between 0 and 1)
arr5 = np.random.rand(3,4) 
arr5

array([[0.45430308, 0.10843553, 0.70998376, 0.84247976],
       [0.02837996, 0.9753799 , 0.30030348, 0.42860638],
       [0.08729008, 0.70106949, 0.22899752, 0.46543697]])

In [29]:
#ones_like - Return a ones-matrix of same shape as input matrix
print(np.ones_like([[2,2,2],[5,7,8]])) 

[[1 1 1]
 [1 1 1]]


In [30]:
#Creates an array of given range 'n'. Default is 0 to n-1.
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(5,16) 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
#Here 2 is the step size.
np.arange(5,16,2) 

array([ 5,  7,  9, 11, 13, 15])

In [33]:
#Linearly spaced array, here 3 is the number of division to make.
np.linspace(10,20,3) 

array([10., 15., 20.])

In [34]:
# Using python method to copy.
arr_copy = arr2.copy()
arr_copy

array([[1, 2],
       [3, 4]])

# Properties and Arrtributes

Some Important Numpy attributes (methods).

1. ndim
2. shape
3. size
4. itemsize
5. dtype
6. astype()

In [35]:
print(arr1)

print('\n')
print(arr2)
print('\n')
print(arr3)

[1 2 3 4 5]


[[1 2]
 [3 4]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
# ndim - Dimension of an array.
print(arr1.ndim) #Vector
print(arr2.ndim) #Matrix
print(arr3.ndim) #Tensor

1
2
2


In [37]:
# shape - Number of items in rows and columns of the array.
print(arr1.shape) 
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 2)
(2, 3)


In [38]:
# size - Prints number of elements inside the array. (Simply Multiply the shape.)

print(arr1.size)
print(arr2.size)


5
4


In [39]:
# itemsize - Prints the size (memory consumption) of one element of that array. 
# Like a float is 8 bytes, sizes may differ in different environment.

print(arr1.itemsize) #int16 - 2 bytes
print(arr3.itemsize) #int64 - 8 bytes
print(arr3.itemsize) #float64 - 8 bytes

2
8
8



Data type	Description

bool_	Boolean (True or False) stored as a byte

int_	Default integer type (same as C long; normally either int64 or int32)

intc	Identical to C int (normally int32 or int64)

intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8	Byte (-128 to 127)

int16	Integer (-32768 to 32767)

int32	Integer (-2147483648 to 2147483647)

int64	Integer (-9223372036854775808 to 9223372036854775807)

uint8	Unsigned integer (0 to 255)

uint16	Unsigned integer (0 to 65535)

uint32	Unsigned integer (0 to 4294967295)

uint64	Unsigned integer (0 to 18446744073709551615)

float_	Shorthand for float64.

float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex_	Shorthand for complex128.

complex64	Complex number, represented by two 32-bit floats

complex128	Complex number, represented by two 64-bit floats

In [40]:
# dtype - Gives the datatype of the array elements (remember homogenous).

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int16
int64
float64


In [41]:
# dtype - We can also use dtype while initiallizing an array 
# with datatype of our choice(size).

# Recreating 2-dimension
arr2 = np.array([[[1,2],[3,4]]],dtype='int32')
print(arr2.dtype)
print(arr2.itemsize)

#Be clever and save space and time by using ideal datatype.
#For example we can use uint8 for human age, as it will always 
# be positive and ususally doesn't goes beyond 120.

int32
4


In [42]:
# astype - We can also change the data type by using this method.

print(arr1.dtype)

arr1 = arr1.astype('int64') 

print(arr1.dtype)

int16
int64


In [43]:
#Python dir() Function
# The dir() function returns all properties and methods of the 
# specified object, without the values. This function will return 
# all the properties and methods, even built-in properties which 
# are default for all object.

dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


# List vs Array

How n-D Array's are better than Lists for large numerical datasets

1. Faster
2. Convenient
3. Less Memory

In [44]:
import sys
list_a = list(range(100))
np_arr = np.arange(100)

In [45]:
print(sys.getsizeof(87)*len(list_a)) 
#getsizeof tells the memory consumed by a particular item, 
# here we multiplied that with total number of such items, i.e., 100.

2800


In [46]:
print(np_arr.itemsize*np_arr.size) 
# here we can see that we are already saving a 
# lot of space by using numpy arrays.

800


In [47]:
x = range(1000000)
y = range(1000000,2000000)

In [48]:
%%time
c = [x+y for x,y in zip(x,y)]
# We cannot directly add so we have to do iteration here.

CPU times: user 39.1 ms, sys: 5.7 ms, total: 44.8 ms
Wall time: 47.7 ms


In [49]:
a = np.arange(1000000)
b = np.arange(1000000,2000000)

In [50]:
%%time
c = a + b

CPU times: user 10 ms, sys: 6.11 ms, total: 16.1 ms
Wall time: 16.9 ms


# Array Operations

In [51]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

### Scalar Operation


In [ ]:
# Arithemetic operation every element with a scaler quantity (basically a number).

print(a1 + 4,"\n")
print(a1 - 1,"\n")
print(a1 * 3,"\n")
print(a1 / 4,"\n")
print(a1 // 5,"\n")
print(a1 % 9,"\n")
print(a1 ** 2,"\n")

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]] 

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]] 

[[0.   0.25 0.5  0.75]
 [1.   1.25 1.5  1.75]
 [2.   2.25 2.5  2.75]] 

[[0 0 0 0]
 [0 1 1 1]
 [1 1 2 2]] 

[[0 1 2 3]
 [4 5 6 7]
 [8 0 1 2]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 



In [69]:
# Relational Operations - Comparision of every element with a scalar.

print(a1 > 1, '\n')
print(a1 >= 3, '\n')
print(a2 < 15, '\n')
print(a2 <= 20, '\n')
print(a1 == 5, '\n')
print(a1 != 2, '\n')


[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[ True  True  True False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]] 

[[False False False False]
 [False  True False False]
 [False False False False]] 

[[ True  True False  True]
 [ True  True  True  True]
 [ True  True  True  True]] 



### Vector Operations (Shape must be same for both)

In [74]:
# Arithemetic operation - Element wise operations.
print(a1 +  a2,"\n")
print(a1 -  a2,"\n")
print(a1 *  a2,"\n")
print(a1 /  a2,"\n")
print(a1 // a2,"\n")
print(a1 %  a2,"\n")
print(a2 ** a1,"\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]] 

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[              1              13             196            3375]
 [          65536         1419857        34012224       893871739]
 [    25600000000    794280046581  26559922791424 952809757913927]] 



In [75]:
# Relational Operations - Elementwise comparision of every element.

print(a1 >  a2, '\n')
print(a1 >= a2, '\n')
print(a2 <  a2, '\n')
print(a2 <= a2, '\n')
print(a1 == a2, '\n')
print(a1 != a2, '\n')


[[False False False False]
 [False False False False]
 [False False False False]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 



### Mathematical Operations - Min / Max / Sum / Prod

In [81]:
# For the entire tensor
print(np.max(a1))
print(np.min(a1))
print(np.sum(a2))
print(np.prod(a2))

11
0
210
647647525324800


In [ ]:
# For each row/column, not entire tensor.
# Use axis, 0 means columns, 1 means rows

print(np.max(a1 ,axis = 0),"\n")
print(np.min(a1 ,axis = 0),"\n")
print(np.sum(a1 ,axis = 0),"\n")
print(np.prod(a1,axis = 0),"\n")

[ 8  9 10 11] 

[0 1 2 3] 

[12 15 18 21] 

[  0  45 120 231] 



### Statistical Operation - Mean / Median / Std / Var

In [ ]:
# For the entire tensor

print(np.mean(a1))
print(np.median(a1))
print(np.std(a2))
print(np.var(a2))

5.5
5.5
3.452052529534663
11.916666666666666


In [89]:
# For each row/column, not entire tensor.
# Use axis, 0 means columns, 1 means rows

print(np.mean(a1 ,axis = 0),"\n")
print(np.median(a1 ,axis = 0),"\n")
print(np.std(a1 ,axis = 0),"\n")
print(np.var(a1,axis = 0),"\n")

[4. 5. 6. 7.] 

[4. 5. 6. 7.] 

[3.26598632 3.26598632 3.26598632 3.26598632] 

[10.66666667 10.66666667 10.66666667 10.66666667] 



### Trignometric / Logs / Exponents / Dot Product

In [26]:
print(np.sin(a1),"\n")

print(np.log(a2),"\n")

print(np.exp(a1),"\n")

# print(np.dot(a1,a2)) 
# # This will fail cause it doesn't obeys the dot product rule.

NameError: name 'a1' is not defined

### Round / Floor / Ceil

In [ ]:
a3 = np.random.random((2,3))*100
print(a3,"\n")

print(np.round(a3,decimals=2),"\n") #rounds upto a desired num of decimal place.

print(np.floor(a3),"\n") #Removes the decimal part without changing whole.

print(np.ceil(a3),"\n") #Next Heightest integer

[[63.19508255 78.98275927 90.72706602]
 [31.04935851 59.46317954 90.33461851]] 

[[63.2  78.98 90.73]
 [31.05 59.46 90.33]] 

[[63. 78. 90.]
 [31. 59. 90.]] 

[[64. 79. 91.]
 [32. 60. 91.]] 

